### PR TITLE
Rails 6.1 compatibility

### PR DESCRIPTION
**Pull request by jarthod**
Hey @elhu :wave:

I just tried upgrading to Rails 6.1 and I had the usual problem again, they added some huge object to the `process_action.action_controller` notification (whole `request` and `response` objects) which on top of that are recursive so they can't be serialized.

This is how it looks:
```
stack level too deep (SystemStackError)
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:175:in `dup'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `each'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `each'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:58:in `as_json'
... (repeated hundreds of time) ...
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `each'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `each'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:174:in `as_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:35:in `encode'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:22:in `encode'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:43:in `to_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/logstash-event-1.2.02/lib/logstash/event.rb:169:in `to_json'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/peastash-0.2.6/lib/peastash/outputs/io.rb:27:in `dump'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/peastash-0.2.6/lib/peastash.rb:88:in `block in log'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/peastash-0.2.6/lib/peastash.rb:21:in `safely'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/peastash-0.2.6/lib/peastash.rb:85:in `log'
/home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/peastash-0.2.6/lib/peastash/middleware.rb:13:in `call'
... (previous middlewares) ...
```

I tracked this down to blacklist these two new attributes and now it's working great :+1: 

I see the specs are quite outdated (and you created #14 for that earlier), I can have a look at updating this if you want, but first you would need to migrate the project to travis.com at least, because on travis.org it's not gonna work any more (or very slowly).

Let me know if you want me to change anything.
Thanks in advance!

### CODE REVIEW

**Comment by elhu** [comment]
Hey @jarthod!

Thanks for the PR. I've juste updated the build process to use Circle CI instead, and simplified the build matrix.
Could you rebase your branch, and add rails 6 to the build matrix please?

PS: The railtie specs are temporarily disabled until I can figure out how to make them work again on Circle CI.

**Comment by jarthod** [comment]
Ok I just rebased master, fixed the Railties test by cleaning up the dummy app (and removed a bunch of useless stuff).
Now they work fine on 4.2, 5.2, 6.0 and 6.1. I also confirmed that the rails 6.1 railtie test fail without my fix:
```
> be --gemfile=gemfiles/Gemfile.rails-6.1.x rspec
...................FFF............................

Failures:

  1) Peastash::Railtie correctly configured with regular conf params logging doesn't log the parameters if log_parameters isn't true
     Failure/Error: (Rails.application.call env_for(path)).tap do |res|
     SystemStackError:
       stack level too deep
     # ./lib/peastash/outputs/io.rb:27:in `dump'
     # ./lib/peastash.rb:88:in `block in log'
     # ./lib/peastash.rb:21:in `safely'
     # ./lib/peastash.rb:85:in `log'
     # ./lib/peastash/middleware.rb:13:in `call'
     # ./spec/peastash/rails_ext/railtie_spec.rb:83:in `perform_request'
     # ./spec/peastash/rails_ext/railtie_spec.rb:62:in `block (5 levels) in <top (required)>'

  2) Peastash::Railtie correctly configured with regular conf params logging logs the parameters if log_parameters is true
     Failure/Error: (Rails.application.call env_for(path)).tap do |res|
     SystemStackError:
       stack level too deep
     # ./lib/peastash/outputs/io.rb:27:in `dump'
     # ./lib/peastash.rb:88:in `block in log'
     # ./lib/peastash.rb:21:in `safely'
     # ./lib/peastash.rb:85:in `log'
     # ./lib/peastash/middleware.rb:13:in `call'
     # ./spec/peastash/rails_ext/railtie_spec.rb:83:in `perform_request'
     # ./spec/peastash/rails_ext/railtie_spec.rb:68:in `block (5 levels) in <top (required)>'

  3) Peastash::Railtie correctly configured with regular conf params logging doesn't log filtered parameters in clear text
     Failure/Error: (Rails.application.call env_for(path)).tap do |res|
     SystemStackError:
       stack level too deep
     # ./lib/peastash/outputs/io.rb:27:in `dump'
     # ./lib/peastash.rb:88:in `block in log'
     # ./lib/peastash.rb:21:in `safely'
     # ./lib/peastash.rb:85:in `log'
     # ./lib/peastash/middleware.rb:13:in `call'
     # ./spec/peastash/rails_ext/railtie_spec.rb:83:in `perform_request'
     # ./spec/peastash/rails_ext/railtie_spec.rb:74:in `block (5 levels) in <top (required)>'

Finished in 0.29323 seconds
50 examples, 3 failures
```
Finally, in order not to multiply the number of text matrix to much (with 3 ruby and 4 rails versions), I changed this to only test one ruby version with each rails version. Let me know what you think, I call change this back.

The 4 tests are green on my CircleCI (which I don't know how you can access).

**Review by elhu — APPROVED** [review]
Awesome, thanks a lot! I'll release a new version today and comment on the PR to let you know.

**Comment by elhu** [comment]
The new gem is live, enjoy!

**Comment by jarthod** [comment]
Awesome, thanks for the fast release :rocket: 
This is quite production ready by the way, maybe it should go to v1.0 at some point ;)

**Pull request merged**
