### PR TITLE
fix: should display the backtrace when an error is raised

### PR DESCRIPTION
**Pull request by keysen**
Hello,

Happy new year @elhu, I hope all is fine for your wife and you in Netherlands :)

Here it's a quick pull request to add more debug when there is an exception, we think to have a case where an exception it's raised but hidden by peastash due to this.

Thanks

### CODE REVIEW

**Comment by elhu** [comment]
Hey @keysen!
Happy new year to you too! Everything is fine over here :)

Seems like a good idea, but we might need to limit the size of the backtrace to 15 lines or something like that, it could get quite big otherwise!

**Comment by keysen** [comment]
Not a bad idea indeed. I just limited to 30 lines because sometimes the mongo exception output is quite big :).

I also made some fixes because my build was not green on travis.

**Comment by keysen** [comment]
@elhu I made the appropriated changes, can you merge my changes and bump your gem :), just tell me when you will have time, it's not in a rush. It's just to know. 

Muchas gracias.

**Comment by elhu** [comment]
Merged! I'll bump the gem version and make a new release tonight, thanks again @keysen!

**Comment by elhu** [comment]
I've released version 0.2.2 of the gem, enjoy!

**Comment by keysen** [comment]
Great! Thanks a lot :).

Have a nice day.

**Pull request merged**
